# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 14f2b8f07c694fc4ea24468ff5b3c1244c06cc9d9eb6c42d215dc7819c76b0c3f3aa0643b9f6365e3134fbce12e491ccb1259f6d51c554fff4c85d7f4ea15beb

test:
  secret_key_base: c08e300660c9f4c55d550b1817ae6fddf2e1471dde5a4740302004d5f87a2968150569e318e9a93d90740df2a4d2c6f527c365fbfbc1d1bfac7a80aea992203b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
